locals {
  enabled_hosts = {
    for name, cfg in var.hosts : name => cfg if cfg.enabled
  }

  selected_commands = var.command_profiles[var.command_profile]
}

resource "local_file" "ssh_config" {
  filename = "${path.module}/ssh_config.generated"
  content = join("\n\n", concat(
    ["# Generated by Terraform. Usage: ssh -F ssh_config.generated <host-alias>"],
    [for name, cfg in local.enabled_hosts : join("\n", compact([
      "Host ${name}",
      "  HostName ${cfg.host}",
      "  User ${cfg.user}",
      "  Port ${cfg.port}",
      cfg.private_key_path != "" ? "  IdentityFile ${pathexpand(cfg.private_key_path)}" : "",
      "  IdentitiesOnly yes",
    ]))]
  ))
  file_permission = "0600"
}

resource "null_resource" "run_profile" {
  for_each = local.enabled_hosts

  triggers = {
    host            = each.value.host
    user            = each.value.user
    port            = tostring(each.value.port)
    command_profile = var.command_profile
    command_hash    = sha256(join("\n", local.selected_commands))
    auth_hint       = each.value.private_key_path != "" ? filesha256(pathexpand(each.value.private_key_path)) : "ssh-agent"
  }

  connection {
    type        = "ssh"
    host        = each.value.host
    user        = each.value.user
    port        = each.value.port
    timeout     = var.connection_timeout
    agent       = each.value.private_key_path == ""
    private_key = each.value.private_key_path != "" ? file(pathexpand(each.value.private_key_path)) : null
  }

  provisioner "remote-exec" {
    inline = local.selected_commands
  }
}

output "managed_hosts" {
  value = {
    for name, cfg in local.enabled_hosts : name => {
      address = cfg.host
      user    = cfg.user
      port    = cfg.port
      tags    = cfg.tags
    }
  }
}

output "command_profile" {
  value = {
    selected = var.command_profile
    commands = local.selected_commands
  }
}

output "ssh_config_file" {
  value = local_file.ssh_config.filename
}
